### ISSUE TITLE
java.io.IOException: DOS header signature not found

### ISSUE THREAD

**Issue by adrelanos** [SSLcom/esigner-codesign#7]
[`hello.pas`](https://github.com/adrelanos/codesigner-test/blob/main/hello.pas):

```
program helloWorld(output);
begin
  writeLn('Hello, World!')
end.
```

Compiler installation:

    sudo apt install fpc

[compile](https://github.com/adrelanos/codesigner-test/blob/main/compile):

    ppcx64 hello.pas -ohello.exe

Check mime type.

    mimetype hello.exe

> hello.exe: application/x-ms-dos-executable

I also have a precompiled exe here: [`hello.exe`](https://github.com/adrelanos/codesigner-test/blob/main/hello.exe)

It's possible to execute the `hello.exe` using `wine`.

    sudo apt install wine
    wine ./hello.exe

> Hello, World!

sign command:

```
/home/runner/work/codesigner-test/codesigner-test/codesign/CodeSignTool-v1.2.7/CodeSignTool.sh sign -username=*** -*** -credential_id=*** -totp_secret=*** -input_file_path=/home/runner/work/codesigner-test/codesigner-test/example/hello.exe -output_dir_path=/home/runner/work/codesigner-test/codesigner-test/artifacts -malware_block=false
```

results:

```
2023-07-13T04:59:45.8350219Z java.io.IOException: DOS header signature not found
2023-07-13T04:59:45.8352490Z 	at net.jsign.pe.PEFile.<init>(PEFile.java:131)
2023-07-13T04:59:45.8353603Z 	at net.jsign.pe.PEFile.<init>(PEFile.java:113)
2023-07-13T04:59:45.8355857Z 	at com.ssl.code.signing.tool.commands.SignCommand.getCodeHash(SignCommand.java:397)
2023-07-13T04:59:45.8357386Z 	at com.ssl.code.signing.tool.commands.SignCommand.run(SignCommand.java:231)
2023-07-13T04:59:45.8358497Z 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
2023-07-13T04:59:45.8362168Z 	at picocli.CommandLine.access$1300(CommandLine.java:145)
2023-07-13T04:59:45.8363165Z 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
2023-07-13T04:59:45.8364174Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
2023-07-13T04:59:45.8418152Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
2023-07-13T04:59:45.8419408Z 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
2023-07-13T04:59:45.8420785Z 	at picocli.CommandLine.execute(CommandLine.java:2078)
2023-07-13T04:59:45.8421490Z 	at com.ssl.code.signing.tool.CodeSignTool.main(CodeSignTool.java:37)
2023-07-13T04:59:45.8711848Z 
2023-07-13T04:59:45.8754034Z ##[error]Something Went Wrong. Please try again.
```

Is this an issue with CodeSignTool or freepascal fpc?

**Comment by bayrakmustafa** [comment]
@adrelanos When I examined the hello.exe file on hex editor, I saw that the first byte values were wrong. In the exe file format, the first bytes must be M or Z. In the example screenshot, there are the results of hello.exe that you sent and an exe file running on windows. I think the problem is related to freepascal. Also, I could not run the hello.exe application on Windows 10 and above. Maybe you can test it on Windows7

**hello.exe:**

![Exe-2](https://github.com/SSLcom/esigner-codesign/assets/11867041/5f64ffce-dda8-44e6-aba8-edebe33c0408)


**sample exe running on windows:**

![Exe-1](https://github.com/SSLcom/esigner-codesign/assets/11867041/ef6ad473-8cbc-42f8-8dfb-45b8126ce753)

**Comment by adrelanos** [comment]
Thank you! Much appreciated! I fixed my compilation command.

    fpc hello.pas -ohello.exe -TWin64

The invalid DOSS header signature error is resolved and signing succeeded.
